# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Swoope Volunteer Fire Company
email: svfc@swoopefire.com
description: >- # this means to ignore newlines until "baseurl:"
  Swoope Volunteer Fire Comapny
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

collections_dir: pages
collections:
  members:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title
  calls:
    output: true
    permalink: /:collection/:name
  apparatus:
    output: true
    permalink: /:collection/:name


exclude:
  - Templates
  - UserEditor
call_threshhold: 30

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
