# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'pages/_posts/'
    fields:
      - { name: Title }
  - name: 'calls'
    label: 'Calls'
    folder: 'pages/calls/'
    fields:
      - { name: Title }
  - name: 'members'
    label: 'Members'
    folder: 'pages/members/'
    fields:
      - { name: Title }
  - name: 'posts'
    label: 'Apparatus'
    folder: 'pages/_posts/'
    fields:
      - { name: Title }